---
- name: add group "jenkins"
  group: name=jenkins

- name: add user "jenkins"
  user: name=jenkins groups=jenkins,wheel home=/var/lib/jenkins createhome=yes
  become: True
  become_method: sudo

- name: add wheel group to sudoers without password
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    state: present

- name: add wheel to the allowed groups in sshd configs
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AllowUsers"
    line: "AllowUsers {{usernames | join(' ')}}"

- local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH delay=10

- name: apply changes in sshd config
  service:
    name: sshd
    state: reloaded

- name: add jenkins authorized keys
  authorized_key: user=jenkins state=present key="{{ lookup('file', 'files/jenkins.pub')}}"

- name: get jenkins repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: 0440

- name: import jenkins rpm key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins-ci.org.key

- name: add jenkins repo
  yum_repository:
    name: jenkins
    description: jenkins YUM repo
    file: jenkins.repo
    baseurl: https://pkg.jenkins-ci.org/redhat/jenkins.repo
    enabled: yes

- name: Install jenkins - this might take awhile
  yum: name=jenkins state=present
  timeout: 600

- name: import EPEL 6 rpm key
  rpm_key:
    state: present
    key: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6


- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/


- name: Install yum packages - increased timeout as this might take a while
  yum: name={{ item }} state=latest
  timeout: 600
  with_items:
    - libxslt-devel
    - python-pip
    - python-devel
    - gcc

- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

- name: Install lxml required by the xml ansible module
  pip:
    name: lxml

- name: Start jenkins servers
  service:
    name: jenkins
    state: started

- name: Wait for admin config to be created
  wait_for:
    path: /var/lib/jenkins/users/admin/config.xml


- name: setup admin authentication 1.
  xml:
    path: /var/lib/jenkins/users/admin/config.xml
    xpath: /user/properties
    add_children:
      - jenkins.security.LastGrantedAuthoritiesProperty

- name: setup admin authentication 2.
  xml:
    path: /var/lib/jenkins/users/admin/config.xml
    xpath: /user/properties/jenkins.security.LastGrantedAuthoritiesProperty
    add_children:
      - roles: ""
      - timestamp: "{{ ansible_date_time.epoch }}"

- name: setup admin authentication 3.
  xml:
    path: /var/lib/jenkins/users/admin/config.xml
    xpath: /user/properties/jenkins.security.LastGrantedAuthoritiesProperty/roles
    add_children:
      - string: authenticated

- name: disable jenkins security
  xml:
    path: /var/lib/jenkins//config.xml
    xpath: /hudson/useSecurity
    value: 'false'

- name: Start jenkins servers
  service:
    name: jenkins
    state: restarted
